web:
  build: .
  command: php -S 0.0.0.0:8000 -t /code
  ports:
    - "8000:8000"
  links:
    - db
  volumes:
    - .:/code
db:
  image: tutum/mysql:latest
  #volumes:
  #  - /Users/luya/Documents/workspace/stopvideogame-docker/data:/var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    ON_CREATE_DB: "wordpress"
    MYSQL_PASS: "wordpress"
